name = "ChainModels"
uuid = "63c4e67a-d9f4-4de5-9a91-57c0b98e2989"
version = "0.1.1"
authors = ["stecrotti <s.crotti@outlook.com>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25"
InvertedIndices = "1.3.1"
LinearAlgebra = "1.9"
LogExpFunctions = "0.3"
OffsetArrays = "1.9"
Random = "1.9"
StatsBase = "0.34"
julia = "1.9"
